### ISSUE TITLE
Not using the python in PATH

### ISSUE THREAD

**Issue by mike-hearn** [neoclide/coc-python#21]
My coc-settings.json has no python settings at all (i.e. it's a blank slate), and my virtualenv is activated (in other words `$VIRTUAL_ENV` has a value).

Despite this, it's showing every sign of not properly identifying the virtualenv python path:

* Throwing "unresolved-import" warnings on packages that are definitely installed in the virtualenv
* Unable to auto-complete on packages that are definitely installed

As an example, from within the python shell I can run `from django.db import models`, but then immediately opening neovim, with a file that contains that line, throws an "unresolved-import".

Here's a quick GIF showing the issue:

![coc-problems](https://user-images.githubusercontent.com/1016999/55291486-f7e57080-53ac-11e9-99bc-a5004cf2922c.gif)

**Comment by gugahoa** [comment]
I believe this could be related to #20

**Comment by chemzqm** [comment]
Fixed, environment rule is added.

**Comment by wadkar** [comment]
This looks like broken again after PR #143 got merged. It is not clear what the PR hopes to achieve given it's description is not in English. But it looks like it is trying to activate environment differently based on whether the shell is fish or not.

Can you please point me to the code that sets VIRTUAL_ENV variable and let me see if I can fix it?

**Comment by atgmello** [comment]
I can confirm to be facing this same issue, albeit with conda environments.

**Comment by wadkar** [comment]
@atgmello are you using `pyenv`? How are you activating/using the virtualenv?

**Comment by atgmello** [comment]
@wadkar No, I'm using conda for both installing packages and managing my environments, so I activate a given env with `conda activate env`.

**Comment by wadkar** [comment]
@atgmello that's interesting. I believe the issue is due to the way with which one detects whether a virtual environment is active or not. Can you try and use the CoC command to set python interpret and point to the conda environment?

**Comment by atgmello** [comment]
Well, turns out this was on me. After running a `:checkhealth` I noticed that neovim wasn't finding the Python provider.  So I created a new conda env, installed `pynvim` and linked to it with `let g:python_host_prog  = '/path/to/python'` (and the same for python3 as well) in my init.vim. With that the issue seemed to be over, I could for instance get autocompletion for pandas, which wasn't happening before. However, running `:checkhealth` again I ran into this wierd `import pynvimImportError: bad magic number in 'pynvim': b'\x03\xf3\r\n'`, but I guess that's another issue altogether.

**Comment by wadkar** [comment]
Huh. Well, I don't use conda but I do manage separate virtualenv for neovim and `let g:python3_host_prog = $HOME . '/pyenv/versions/.../python3'` . But I still get this error.

@chemzqm can you please let us know what are we missing here? What information can we provide you so that it's easy to debug for you?
