### ISSUE TITLE
Jedi ignores extra paths

### ISSUE THREAD

**Issue by radimsuckr** [neoclide/coc-python#230]
I've got following extra paths configuration in my CocConfig.

```json
"python.autoComplete.extraPaths": [
	"./var/site-packages"
]
```

But Jedi ignores this as an extra path while MPLS works just fine with it. How do I configure Jedi autocompletion to use relative directories for autocompletion? I've got Jedi in version `0.17.0-1`.

**Comment by theangryangel** [comment]
The fix was merged into master under https://github.com/neoclide/coc-python/pull/201, but it's not been released yet.

If you need to run with this fix, until coc-python has a release, the following should work

1. Install coc-python like normal
2. Head to your ~/.config/coc/extensions/node_modules/coc-python directory
3. `wget https://patch-diff.githubusercontent.com/raw/neoclide/coc-python/pull/201.patch`
4. `patch -p 1 < 201.patch && rm 201.patch`
6. Restart nvim if it was already running

Alternatively you can run from master
